# JPA
spring:
  profiles:
    include: mysql

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  datasource:
    generate-unique-name: false

logging:
  level:
    org:
      hibernate:
        SQL : debug
        type:
          descriptor:
            sql:
              BasicBinder : TRACE




